module.exports = {
  content: ['./public_html/**/*.html'],
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "surface-container-highest": "#e2e1ee",
                      "on-secondary-fixed": "#00201d",
                      "surface-container": "#ededf9",
                      "on-error-container": "#93000a",
                      "surface-bright": "#fbf8ff",
                      "on-tertiary-fixed-variant": "#3f465c",
                      "stress-alert": "#FF6B6B",
                      "on-tertiary": "#ffffff",
                      "on-primary-fixed-variant": "#0037b9",
                      "on-primary": "#ffffff",
                      "on-error": "#ffffff",
                      "tertiary-container": "#60687f",
                      "surface-tint": "#1c4ee3",
                      "secondary-fixed-dim": "#5adace",
                      "on-surface": "#191b24",
                      "inverse-surface": "#2e3039",
                      "outline": "#747687",
                      "on-tertiary-container": "#e3e8ff",
                      "inverse-on-surface": "#f0effc",
                      "on-background": "#191b24",
                      "primary-container": "#2d5aee",
                      "surface-dim": "#d9d9e5",
                      "error-container": "#ffdad6",
                      "soft-navy": "#1E293B",
                      "on-primary-container": "#e6e8ff",
                      "primary": "#003fd0",
                      "outline-variant": "#c4c5d8",
                      "on-surface-variant": "#434655",
                      "on-secondary-container": "#007169",
                      "tertiary-fixed": "#dae2fd",
                      "surface-container-lowest": "#ffffff",
                      "lavender-haze": "#EBEBFF",
                      "error": "#ba1a1a",
                      "on-primary-fixed": "#001453",
                      "surface": "#fbf8ff",
                      "secondary-fixed": "#79f7ea",
                      "on-secondary-fixed-variant": "#00504a",
                      "tertiary-fixed-dim": "#bec6e0",
                      "on-tertiary-fixed": "#131b2e",
                      "on-secondary": "#ffffff",
                      "seafoam-light": "#E6FFFA",
                      "surface-container-low": "#f3f2ff",
                      "secondary": "#006a63",
                      "tertiary": "#485066",
                      "surface-variant": "#e2e1ee",
                      "primary-fixed": "#dde1ff",
                      "inverse-primary": "#b8c4ff",
                      "background": "#fbf8ff",
                      "secondary-container": "#79f7ea",
                      "primary-fixed-dim": "#b8c4ff",
                      "surface-container-high": "#e8e7f3"
              },
              "borderRadius": {
                      "DEFAULT": "0.25rem",
                      "lg": "0.5rem",
                      "xl": "0.75rem",
                      "full": "9999px"
              },
              "spacing": {
                      "gutter": "24px",
                      "base": "8px",
                      "margin-mobile": "16px",
                      "container-max": "1200px",
                      "stack-sm": "12px",
                      "stack-lg": "48px",
                      "stack-md": "24px"
              },
              "fontFamily": {
                      "body-md": ["Plus Jakarta Sans"],
                      "headline-lg": ["Plus Jakarta Sans"],
                      "headline-md": ["Plus Jakarta Sans"],
                      "body-lg": ["Plus Jakarta Sans"],
                      "headline-lg-mobile": ["Plus Jakarta Sans"],
                      "display-lg": ["Plus Jakarta Sans"],
                      "label-sm": ["Hanken Grotesk"]
              },
              "fontSize": {
                      "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                      "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                      "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                      "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                      "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
                      "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                      "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
              }
            },
          },
        }
